[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run build && npx serve -s dist -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
