# Development Database Setup
# Run this with: docker-compose up -d
# Backend should be run directly on host during development

services:
  persistant_volume_db:
    image: postgres:16
    container_name: carmodpicker_persistant_volume_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - carmodpicker_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  test_db:
    image: postgres:16
    container_name: carmodpicker_test_db
    env_file:
      - .env.test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  carmodpicker_data:
