name: Backend CI

on:
  push:
    branches: [main, develop]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    branches: [main, develop]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov black isort mypy

      - name: Run linting
        run: |
          cd backend
          black --check --diff .

      - name: Run type checking
        run: |
          cd backend
          mypy app/ --ignore-missing-imports

      - name: Run tests with coverage
        env:
          SECRET_KEY: test-secret-key-for-ci
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: 30
          ALLOWED_ORIGINS: http://localhost:3000,http://localhost:4000
          DEBUG: true
          PROJECT_NAME: CarModPicker API
          API_STR: /api/v1
          SENDGRID_API_KEY: test-key
          EMAIL_FROM: test@example.com
          SENDGRID_VERIFY_EMAIL_TEMPLATE_ID: test-verify-template
          SENDGRID_RESET_PASSWORD_TEMPLATE_ID: test-reset-template
        run: |
          cd backend
          pytest --cov=app --cov-report=xml --cov-report=term-missing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./backend/coverage.xml
          flags: backend
          name: backend-coverage
